In [2]:
import numpy as np
arr = np.zeros((2,2))
arr

array([[0., 0.],
       [0., 0.]])

In [3]:
import numpy as np
arr = np.ones((4,2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
import numpy as np
arr = np.full((4,4),5)
arr

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [7]:
import numpy as np
arr = np.array([[1,2,3],[1,2,3]])
new_arr = np.zeros_like(arr)
print(arr)
print(new_arr)

[[1 2 3]
 [1 2 3]]
[[0 0 0]
 [0 0 0]]


In [11]:
import numpy as np
arr = np.array([[1,2,3],[1,2,3]])
new_arr = np.ones_like(arr)
print(arr)
print(new_arr)

[[1 2 3]
 [1 2 3]]
[[1 1 1]
 [1 1 1]]


In [15]:
import numpy as np
new_list = [1,2,3,4]
arr = np.array(new_list)
print(new_list)
print(arr)

[1, 2, 3, 4]
[1 2 3 4]


In [25]:
import numpy as np

array = np.arange(10, 50)
print("Array with values arranging from 10 to 49:")
print(array)


Array with values arranging from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [26]:
matrix = np.arange(9).reshape(3, 3)
print("\n3x3 matrix with values ranging from 0 to 8: ")
print(matrix)


3x3 matrix with values ranging from 0 to 8: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
identity_matrix = np.eye(3)
print("\n3x3 identity matrix: ")
print(identity_matrix)



3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom array of size 30: ")
print(random_array)
print("\nMean of the array: ")
print(mean_value)


Random array of size 30: 
[0.73862186 0.48772698 0.10095076 0.57567103 0.99897535 0.84521461
 0.86767384 0.00583828 0.07294378 0.82444107 0.83223869 0.81094233
 0.42000083 0.61867647 0.09115007 0.33154937 0.50798538 0.03707563
 0.22276115 0.70402635 0.53990168 0.77645572 0.319968   0.23080425
 0.56571621 0.55100776 0.55368257 0.92488582 0.46446989 0.17479199]

Mean of the array: 
0.5065382574841963


In [20]:
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 array with random values:")
print(random_10x10)
print("\nMinimum value in the array:")
print(min_value)
print("\nMaximum value in the array:")
print(max_value)



10x10 array with random values:
[[0.76963519 0.60102047 0.04330053 0.40563226 0.13103438 0.19620449
  0.62160333 0.75121487 0.90364599 0.17494562]
 [0.36433326 0.36749852 0.17957997 0.73754841 0.30779746 0.20226499
  0.47324559 0.0447999  0.39753193 0.27584849]
 [0.35039614 0.50180221 0.88664799 0.4287858  0.2889915  0.43769695
  0.0467333  0.36140195 0.60091271 0.25129858]
 [0.94714681 0.09424424 0.55025174 0.69318366 0.17002658 0.12152655
  0.00900391 0.53472495 0.28508192 0.15984817]
 [0.41618917 0.28213991 0.02425804 0.40803041 0.83598609 0.85107905
  0.88854214 0.81586339 0.82658949 0.75669001]
 [0.21149117 0.97927272 0.11902737 0.14237478 0.78841851 0.24588821
  0.14454841 0.63552742 0.80143474 0.11633141]
 [0.47647687 0.08907174 0.36351998 0.18929808 0.28921802 0.16810212
  0.32874331 0.07758755 0.47480629 0.75746021]
 [0.77011948 0.62564711 0.96888044 0.49375979 0.11681011 0.26805778
  0.84046028 0.3565388  0.50766226 0.59812605]
 [0.78286153 0.85514525 0.27143098 0.36280252 0

In [21]:
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero array of size 10 with the 5th element replaced by 1:")
print(zero_array)



Zero array of size 10 with the 5th element replaced by 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [22]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed array:")
print(reversed_arr)



Reversed array:
[0 4 0 0 2 1]


In [23]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D array with 1 on the border and 0 inside:")
print(border_array)



2D array with 1 on the border and 0 inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 matrix with a checkerboard pattern:")
print(checkerboard)



8x8 matrix with a checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
x = np.array([[1, 2], [3, 5]]) 
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [30]:
import numpy as np
x = np.array([[1, 2], [3, 5]]) 
y = np.array([[5, 6], [7, 8]])
add_xy = np.add(x, y)
print("Addition of x and y:\n", add_xy)

Addition of x and y:
 [[ 6  8]
 [10 13]]


In [31]:
import numpy as np
x = np.array([[1, 2], [3, 5]]) 
y = np.array([[5, 6], [7, 8]])
subtract_xy = np.subtract(x, y)
print("Subtraction of x and y:\n", subtract_xy)


Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]


In [32]:
import numpy as np
x = np.array([[1,2],[3,5]])
multiply_x = x * 2
print("Multiplication of x with 2:\n", multiply_x)


Multiplication of x with 2:
 [[ 2  4]
 [ 6 10]]


In [33]:
import numpy as np
x = np.array([[1, 2], [3, 5]]) 
square_x = np.square(x)
print("Square of each element in x:\n", square_x)

Square of each element in x:
 [[ 1  4]
 [ 9 25]]


In [34]:
import numpy as np
x = np.array([[1, 2], [3, 5]]) 
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
dot_vw = np.dot(v, w)
print("Dot product of v and w:\n", dot_vw)

dot_xv = np.dot(x, v)
print("Dot product of x and v:\n", dot_xv)

dot_xy = np.dot(x, y)
print("Dot product of x and y:\n", dot_xy)


Dot product of v and w:
 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


In [36]:
import numpy as np
x = np.array([[1, 2], [3, 5]]) 
v = np.array([9, 10])
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Concatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("Error:", e)


Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
